######################################################################
# Automatically generated by qmake (2.01a) ter Out 10 15:56:14 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += link_pkgconfig
PKGCONFIG = opencv 

# Input
HEADERS += animate.hpp qcustomplot.h
FORMS += video-analyser.ui
SOURCES += animate.cpp main.cpp qcustomplot.cpp
